
services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /home/zerg/ai-vault/_stack/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "2222:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - /home/zerg/ai-vault/_stack/openwebui:/app/backend/data
      - /home/zerg/ai-vault:/home/zerg/ai-vault
    depends_on:
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /home/zerg/ai-vault/_stack/qdrant:/qdrant/storage

  ingestion:
    build: ./ingestion-service
    container_name: ingestion
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - /home/zerg/ai-vault:/home/zerg/ai-vault
    depends_on:
      - ollama
      - qdrant

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /:/srv
      - /home/zerg/ai-vault/_stack/filebrowser/database:/database
      - /home/zerg/ai-vault/_stack/filebrowser/config:/config

networks:
  default:
    name: ai-vault-net
